plugins {
    id 'java-library'
    id 'groovy'
    id 'java-test-fixtures'
    id 'maven-publish'
    id "io.curity.gradle.curity-plugin-dev" version "0.3.0"
}

group = 'io.curity'
version = project.hasProperty('version') ? project.property('version') : '0.1.0'

repositories {
    mavenCentral()
}

dependencies {
    compileOnly 'se.curity.identityserver:identityserver.sdk:11.0.0'
    compileOnly 'org.slf4j:slf4j-api:2.0.12'

    api('org.bitbucket.b_c:jose4j:0.9.6') {
        exclude group: 'org.slf4j', module: 'slf4j-api'
    }

    // Test fixtures – these become transitive for consumers of testFixtures(...)
    testFixturesApi 'se.curity.identityserver:identityserver.sdk:11.0.0'
    testFixturesApi 'org.spockframework:spock-core:2.4-M4-groovy-4.0'
    testFixturesImplementation 'org.bitbucket.b_c:jose4j:0.9.6'
    testFixturesApi 'org.slf4j:slf4j-api:2.0.12'
    testFixturesApi 'org.testcontainers:testcontainers:2.0.3'
    testFixturesApi 'org.testcontainers:testcontainers-spock:2.0.3'
    testFixturesApi 'org.htmlunit:htmlunit:4.21.0'

    testFixturesRuntimeOnly 'org.slf4j:slf4j-simple:2.0.12'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withSourcesJar()
    withJavadocJar()
}

tasks.javadoc {
    exclude '**/*Configuration.java'
}


publishing {
    repositories {
        maven {
            name = "CurityPsPackages"
            url = "https://maven.pkg.github.com/curity-ps/curity-ps-sdk-commons"
            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }

    publications {
        gpr(MavenPublication) {
            from(components.java)
        }
    }
}

test {
    useJUnitPlatform()
    testLogging {
        events "started", "passed", "skipped", "failed"
    }
}